blank_issues_enabled: true
contact_links:
  - name: Installation Help
    url: https://orbitone.org/discord
    about: Please join our Discord for help with installation.
  - name: General Question
    url: https://orbitone.org/discord
    about: Please join our Discord for general inquiries.
